# Generated by Django 3.1.7 on 2021-03-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.CharField(max_length=200),
        ),
    ]
